In [1]:
import numpy as np
a = np.array([[4, 3, 5], [1, 2, 1]])
b = np.sort(a, axis=1)
b

array([[3, 4, 5],
       [1, 1, 2]])

In [2]:
a.sort(axis=1)
a

array([[3, 4, 5],
       [1, 1, 2]])

In [3]:
a = np.array([4, 3, 1, 2])
j = np.argsort(a)
j

array([2, 3, 1, 0], dtype=int64)

In [4]:
a[j]

array([1, 2, 3, 4])

In [5]:
a = np.array([4, 3, 1, 2])
j_max = np.argmax(a)
j_min = np.argmin(a)
j_max, j_min

(0, 2)