In [2]:
import numpy as np
a = np.array([1, 2, 3, 4])
a + 1

array([2, 3, 4, 5])

In [3]:
2**a

array([ 2,  4,  8, 16], dtype=int32)

In [4]:
b = np.ones(4) + 1
a - b

array([-1.,  0.,  1.,  2.])

In [5]:
a*b

array([2., 4., 6., 8.])

In [7]:
j = np.arange(5)
2**(j + 1) - j

array([ 2,  3,  6, 13, 28])

In [8]:
a = np.arange(10000)
%timeit a + 1

14.8 µs ± 805 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [9]:
l = range(10000)
%timeit [i+1 for i in l] 

2.08 ms ± 110 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [10]:
c = np.ones((3, 3))
c * c   #bukan matriks multiplication

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [11]:
c.dot(c)

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [12]:
[2**0, 2**1, 2**2, 2**3, 2**4]

[1, 2, 4, 8, 16]

In [15]:
a = np.array([1, 2, 3, 4])
b = np.array([4, 2, 2, 4])
a == b

array([False,  True, False,  True])

In [16]:
a > b

array([False, False,  True, False])

In [17]:
a = np.array([1, 1, 0, 0], dtype=bool)
b = np.array([1, 0, 1, 0], dtype=bool)
np.logical_or(a, b)

array([ True,  True,  True, False])

In [18]:
np.logical_and(a, b)

array([ True, False, False, False])

In [19]:
a = np.arange(5)
np.sin(a)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [20]:
np.log(a)

C:\Users\user\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436])

In [21]:
np.exp(a)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692, 54.59815003])

In [25]:
a = np.arange (4)
a + np.array([1, 2]) 

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [26]:
a = np.triu(np.ones((3, 3)), 1)   # see help(np.triu)
a

array([[0., 1., 1.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [27]:
a.T

array([[0., 0., 0.],
       [1., 0., 0.],
       [1., 1., 0.]])